---
name: s3ninjatest
logging:
  level: DEBUG
director_uuid: 1283c62e-8e7b-43c2-8f97-f42bf8aba812
releases:
- name: s3ninjadev
  version: latest
compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small
update:
  canaries: 1
  canary_watch_time: 5-3000
  update_watch_time: 5-30000
  max_in_flight: 1
  max_errors: 100
networks:
- name: default
  type: dynamic
  cloud_properties:
    security_groups:
    - default
- name: vip_network
  type: vip
  cloud_properties:
    security_groups:
    - default
resource_pools:
- name: common
  network: default
  size: 2
  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: 53
  cloud_properties:
    instance_type: m1.small
  persistent_disk: 8196
jobs:
- name: s3ninja_tester
  templates:
  - name: s3ninja
    release: s3ninjadev
  instances: 1
  resource_pool: common
  networks:
  - name: default
    default:
    - dns
    - gateway
  persistent_disk: 500
properties:
  s3ninja:
    port: 9444
    awsAccessKey: "Foo"
    awsSecretKey: "Bar"
    autocreateBuckets: true
