---
java7/openjdk-1.7.0_51.tar.gz:
  object_id: 09b01a87-2dc6-4ee5-bdce-60299bf60fd1
  sha: !binary |-
    OWU1ZDg2MTYzMDgyNDcwZTRiY2M0YWYwMTI2MGJlMTc3OTk2NDI2OQ==
  size: 10906302
s3ninja/s3ninja-20140425.zip:
  object_id: f7361c82-48f7-4726-9547-23add5a5bea3
  sha: !binary |-
    ZDQyN2U2ODg0ZTJiZGE1MTdjYjgzNTE5YzM2MGFkNTk5YjMxYjdhYg==
  size: 13674821
