meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: s3ninja
    templates:
      - name: s3ninja
        release: s3ninja
      - name: nginx
        release: s3ninja
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties:
  s3ninja: (( merge ))
